//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MF_PruebasSPEI.exMF {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="serviciosMFSoap", Namespace="http://tempuri.org/")]
    public partial class serviciosMF : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback recibeAbonoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cambioEstadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback recibeInstitucionesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public serviciosMF() {
            this.Url = global::MF_PruebasSPEI.Properties.Settings.Default.pruebasSPEI_exMF_serviciosMF;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event recibeAbonoCompletedEventHandler recibeAbonoCompleted;
        
        /// <remarks/>
        public event cambioEstadoCompletedEventHandler cambioEstadoCompleted;
        
        /// <remarks/>
        public event recibeInstitucionesCompletedEventHandler recibeInstitucionesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/recibeAbono", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlDocument recibeAbono(System.Xml.XmlDocument xmlDoc) {
            object[] results = this.Invoke("recibeAbono", new object[] {
                        xmlDoc});
            return ((System.Xml.XmlDocument)(results[0]));
        }
        
        /// <remarks/>
        public void recibeAbonoAsync(System.Xml.XmlDocument xmlDoc) {
            this.recibeAbonoAsync(xmlDoc, null);
        }
        
        /// <remarks/>
        public void recibeAbonoAsync(System.Xml.XmlDocument xmlDoc, object userState) {
            if ((this.recibeAbonoOperationCompleted == null)) {
                this.recibeAbonoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrecibeAbonoOperationCompleted);
            }
            this.InvokeAsync("recibeAbono", new object[] {
                        xmlDoc}, this.recibeAbonoOperationCompleted, userState);
        }
        
        private void OnrecibeAbonoOperationCompleted(object arg) {
            if ((this.recibeAbonoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.recibeAbonoCompleted(this, new recibeAbonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cambioEstado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlDocument cambioEstado(System.Xml.XmlDocument xmlDocument) {
            object[] results = this.Invoke("cambioEstado", new object[] {
                        xmlDocument});
            return ((System.Xml.XmlDocument)(results[0]));
        }
        
        /// <remarks/>
        public void cambioEstadoAsync(System.Xml.XmlDocument xmlDocument) {
            this.cambioEstadoAsync(xmlDocument, null);
        }
        
        /// <remarks/>
        public void cambioEstadoAsync(System.Xml.XmlDocument xmlDocument, object userState) {
            if ((this.cambioEstadoOperationCompleted == null)) {
                this.cambioEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncambioEstadoOperationCompleted);
            }
            this.InvokeAsync("cambioEstado", new object[] {
                        xmlDocument}, this.cambioEstadoOperationCompleted, userState);
        }
        
        private void OncambioEstadoOperationCompleted(object arg) {
            if ((this.cambioEstadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cambioEstadoCompleted(this, new cambioEstadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/recibeInstituciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void recibeInstituciones(System.Xml.XmlDocument xmlInstituciones) {
            this.Invoke("recibeInstituciones", new object[] {
                        xmlInstituciones});
        }
        
        /// <remarks/>
        public void recibeInstitucionesAsync(System.Xml.XmlDocument xmlInstituciones) {
            this.recibeInstitucionesAsync(xmlInstituciones, null);
        }
        
        /// <remarks/>
        public void recibeInstitucionesAsync(System.Xml.XmlDocument xmlInstituciones, object userState) {
            if ((this.recibeInstitucionesOperationCompleted == null)) {
                this.recibeInstitucionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrecibeInstitucionesOperationCompleted);
            }
            this.InvokeAsync("recibeInstituciones", new object[] {
                        xmlInstituciones}, this.recibeInstitucionesOperationCompleted, userState);
        }
        
        private void OnrecibeInstitucionesOperationCompleted(object arg) {
            if ((this.recibeInstitucionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.recibeInstitucionesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void recibeAbonoCompletedEventHandler(object sender, recibeAbonoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class recibeAbonoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal recibeAbonoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlDocument Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlDocument)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void cambioEstadoCompletedEventHandler(object sender, cambioEstadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cambioEstadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cambioEstadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlDocument Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlDocument)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void recibeInstitucionesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591